---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangzhengchun.
--- DateTime: 2023/4/15 10:07
---
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId
if(tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end
if(redis.call('sismember', orderKey, userId) == 1) then
    return 2
end
redis.call('incrby', stockKey, -1)

redis.call('sadd', orderKey, userId)

-- 发送消息到队列中 XDD stream.orders * k1 v1 k2 v2....
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0
